# Generated by Django 3.2.3 on 2021-05-19 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(default='noname', help_text='Enter product name', max_length=256)),
                ('ProductPrice', models.IntegerField(default=0, help_text='Enter product price')),
                ('ProductImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('ProductDescription', models.CharField(default='no description', help_text='Enter product description', max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='BasketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productmodel')),
            ],
        ),
    ]
